# Pandas Part 1: Exploring Real Data with Pandas

In this session, students will not just learn Pandas syntax. They will learn how to **approach a real analytics problem** using a dataset that looks and feels like real business data.

### Business scenario

You are part of the analytics team for a growing specialty beverage retailer. Leadership wants answers to questions such as:

- Which countries and cities generate the most revenue?
- Which product categories sell the most?
- Which channels appear strongest?
- Are there data quality issues we should notice before deeper analysis?
- What should management investigate next?

This session focuses on the very beginning of the analytics workflow:

> **load → inspect → understand → question → explore**

---

## Learning objectives

By the end of this session, students should be able to:

- Load a dataset into a Pandas DataFrame
- Inspect its basic structure, columns, data types, and size
- Distinguish between rows, columns, index, and values
- Use `head()`, `tail()`, `sample()`, `info()`, `describe()`, and `value_counts()`
- Select columns and filter rows
- Sort and summarize data to answer practical business questions
- Identify potential data quality issues before cleaning
- Document observations in a notebook clearly and professionally

## Imports and display options

We will start with the core libraries for this session:
- **pandas** for data manipulation
- **numpy** for numerical support

For session 1, we keep the toolset intentionally simple. The goal is to become comfortable with the **DataFrame**.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

print("Pandas version:", pd.__version__)

Pandas version: 3.0.0

## Load the dataset

This notebook uses a local CSV file packaged with the session materials:

`retail_data.csv`

The dataset is a **realistic retail transactions dataset for teaching**.  
It is designed to mimic the kinds of issues analysts see in practice:
- multiple countries and cities
- multiple product categories
- revenue, discount, and shipping fields
- a few missing values
- a few inconsistent text values
- a few duplicate rows
- some negative quantities that may represent returns

That means students can work on a workflow that closely resembles **real business analytics work**.

In [3]:
df = pd.read_csv("retail_data.csv")
df.head()

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
0,O100002,2024-04-01,C10061,Consumer,Online,Germany,Munich,Europe,Merch,Ceramic Mug,2,14.00,0.00,10.36,28.00
1,O100004,2024-05-07,C10147,Small Business,Marketplace,Australia,Brisbane,APAC,Merch,Tote Bag,3,18.00,0.00,10.78,54.00
2,O100005,2024-03-15,C10303,Corporate,Marketplace,Australia,Melbourne,APAC,Bakery,Biscotti Jar,2,11.50,0.00,9.33,23.00
3,O100006,2024-01-18,C10309,Small Business,Store Pickup,United States,San Jose,North America,Coffee,Colombian Beans,4,16.50,0.00,6.87,66.00
4,O100009,2024-03-26,C10443,Small Business,Marketplace,France,Lyon,Europe,Tea,Matcha Tin,2,19.00,0.00,2.57,38.00

## First impressions

Do not jump into advanced analysis immediately.

A strong analyst first asks:
1. What is one row?
2. What does each column mean?
3. What looks numerical vs categorical?
4. What could be messy, incomplete, or suspicious?
5. What business questions can this dataset answer?

### Discussion prompt
Before running more code, look at the first five rows and discuss:
- What do you think one row represents?
- Which columns are IDs?
- Which columns are likely categorical?
- Which columns are likely numeric?
- Which columns might need cleaning later?

## What is a DataFrame?

A **DataFrame** is a two-dimensional tabular structure:
- rows = observations
- columns = variables/features
- index = row labels

In business analytics, a DataFrame often represents:
- transactions
- customers
- products
- events
- time series records
- survey responses

In [4]:
type(df)

pandas.DataFrame

In [5]:
df.shape

(4512, 15)

### Interpreting `shape`

The output of `shape` gives:

```python
(number_of_rows, number_of_columns)
```

Ask students:
- How many observations do we have?
- Is this a small dataset or large dataset?
- Would we inspect it manually row by row? Why not?

In [6]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'segment', 'channel', 'country', 'city', 'region', 'category',
       'product_name', 'quantity', 'unit_price', 'discount', 'shipping_cost', 'revenue'],
      dtype='str')

In [7]:
df.dtypes

order_id             str
order_date           str
customer_id          str
segment              str
channel              str
country              str
city                 str
region               str
category             str
product_name         str
quantity           int64
unit_price       float64
discount         float64
shipping_cost    float64
revenue          float64
dtype: object

## Core inspection commands

These are among the most important commands in all of Pandas:

- `head()` → first few rows
- `tail()` → last few rows
- `sample()` → random rows
- `info()` → structure, data types, non-null counts
- `describe()` → summary statistics for numeric columns

Students should become fluent with these early.

In [8]:
df.head(10)

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
0,O100002,2024-04-01,C10061,Consumer,Online,Germany,Munich,Europe,Merch,Ceramic Mug,2,14.00,0.00,10.36,28.00
1,O100004,2024-05-07,C10147,Small Business,Marketplace,Australia,Brisbane,APAC,Merch,Tote Bag,3,18.00,0.00,10.78,54.00
2,O100005,2024-03-15,C10303,Corporate,Marketplace,Australia,Melbourne,APAC,Bakery,Biscotti Jar,2,11.50,0.00,9.33,23.00
3,O100006,2024-01-18,C10309,Small Business,Store Pickup,United States,San Jose,North America,Coffee,Colombian Beans,4,16.50,0.00,6.87,66.00
4,O100009,2024-03-26,C10443,Small Business,Marketplace,France,Lyon,Europe,Tea,Matcha Tin,2,19.00,0.00,2.57,38.00
5,O100011,2024-04-12,C10074,Consumer,Marketplace,Germany,Munich,Europe,Equipment,Pour Over Kit,2,34.00,0.00,8.15,68.00
6,O100012,2024-06-16,C10139,Consumer,Online,United Kingdom,Birmingham,Europe,Coffee,Colombian Beans,5,16.50,0.05,4.84,78.38
7,O100014,2024-05-06,C10264,Small Business,Online,United Kingdom,London,Europe,Bakery,Muffin Box,3,13.00,0.00,2.73,39.00
8,O100015,2024-03-03,C10290,Consumer,Online,United States,Chicago,North America,Coffee,Espresso Blend,3,17.50,0.00,8.80,52.50
9,O100018,2024-03-22,C10629,Consumer,Online,Australia,Melbourne,APAC,Bakery,Biscotti Jar,4,11.50,0.00,6.99,46.00

In [10]:
df.tail(10)

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
4502,O100921,2024-02-12,C10059,Consumer,Online,United States,San Jose,North America,Equipment,Milk Frother,1,24.00,0.00,3.88,24.00
4503,O104352,2024-04-10,C10058,Consumer,Online,France,Paris,Europe,Coffee,Ethiopian Beans,4,18.00,0.00,10.72,72.00
4504,O102476,2024-01-14,C10490,Consumer,Online,France,Lyon,Europe,Equipment,Milk Frother,2,24.00,0.00,6.41,48.00
4505,O105898,2024-01-16,C10098,Small Business,Marketplace,Germany,Berlin,Europe,Coffee,Espresso Blend,4,17.50,0.00,8.82,70.00
4506,O106228,2024-05-23,C10471,Small Business,Online,France,Lyon,Europe,Tea,Herbal Tea,1,10.00,0.10,10.83,9.00
4507,O103554,2024-05-30,C10423,Consumer,Online,Germany,Berlin,Europe,Tea,Matcha Tin,-1,19.00,0.00,4.92,-19.00
4508,O105734,2024-06-21,C10188,Consumer,Online,United States,San Jose,North America,Bakery,Croissant Box,3,15.00,0.05,5.08,42.75
4509,O107191,2024-04-19,C10019,Consumer,Store Pickup,Canada,Vancouver,North America,Merch,T-Shirt,2,26.00,0.00,6.88,52.00
4510,O104743,2024-03-26,C10465,Consumer,Online,United States,New York,North America,Coffee,Ethiopian Beans,4,18.00,0.00,4.90,72.00
4511,O107259,2024-01-21,C10602,Consumer,Online,United States,Seattle,North America,Equipment,Milk Frother,4,25.20,0.00,8.62,100.80

In [11]:
df.sample(8, random_state=1)

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
4336,O108654,2024-03-20,C10266,Consumer,Online,Canada,Montreal,North America,Tea,Herbal Tea,2,10.00,0.00,7.22,20.00
4280,O108544,2024-01-29,C10627,Corporate,Online,United States,Austin,North America,Bakery,Croissant Box,4,15.00,0.10,8.84,54.00
4326,O108634,2024-02-03,C10356,Consumer,Online,United States,San Jose,North America,Bakery,Muffin Box,2,13.00,0.00,3.13,26.00
834,O101651,2024-04-21,C10489,Small Business,Marketplace,Canada,Vancouver,North America,Tea,Green Tea,2,12.60,0.00,8.58,25.20
222,O100426,2024-04-23,C10519,Small Business,Marketplace,United Kingdom,Manchester,Europe,Coffee,Colombian Beans,3,16.50,0.00,9.70,49.50
2850,O105654,2024-05-14,C10490,Small Business,Marketplace,United Kingdom,Manchester,Europe,Bakery,Cookie Pack,1,9.00,0.00,4.72,9.00
3436,O106817,2024-05-14,C10314,Consumer,Marketplace,France,Lyon,Europe,Equipment,French Press,1,26.60,0.00,7.76,26.60
1810,O103593,2024-03-20,C10116,Corporate,Marketplace,United Kingdom,Manchester,Europe,Bakery,Biscotti Jar,5,12.08,0.00,3.84,60.38

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4512 entries, 0 to 4511
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       4512 non-null   str
 1   order_date     4512 non-null   str
 2   customer_id    4512 non-null   str
 3   segment        4422 non-null   str
 4   channel        4444 non-null   str
 5   country        4512 non-null   str
 6   city           4512 non-null   str
 7   region         4512 non-null   str
 8   category       4512 non-null   str
 9   product_name   4512 non-null   str
 10  quantity       4512 non-null   int64
 11  unit_price     4512 non-null   float64
 12  discount       4512 non-null   float64
 13  shipping_cost  4467 non-null   float64
 14  revenue        4512 non-null   float64
dtypes: float64(4), int64(1), str(10)
memory usage: 528.9 KB

### Why `info()` matters

`info()` is often the first serious inspection tool an analyst uses because it quickly shows:
- total rows
- total columns
- data types
- missing values
- approximate memory usage

### Questions
- Are all columns complete?
- Which columns may have missing values?
- Does `order_date` look like a date yet?
- Which columns should probably be categorical rather than numeric?

In [13]:
df.describe()

       quantity  unit_price  discount  shipping_cost  revenue
count  4,512.00    4,512.00  4,512.00       4,467.00 4,512.00
mean       2.92       20.22      0.02           7.48    58.24
std        1.54       14.28      0.04           2.89    55.80
min       -2.00        8.55      0.00           2.50  -165.90
25%        2.00       13.00      0.00           5.00    27.00
50%        3.00       16.62      0.00           7.43    47.02
75%        4.00       22.00      0.00           9.98    72.00
max        5.00       82.95      0.15          12.49   414.75

### `describe()` only summarizes numeric columns by default

This is useful, but incomplete. Many business insights are in **categorical variables**.

We can ask Pandas to summarize **all columns**:

In [14]:
df.describe(include="all").T

                 count unique             top  freq  mean   std     min   25%   50%   75%    max
order_id          4512   4500         O100695     2   NaN   NaN     NaN   NaN   NaN   NaN    NaN
order_date        4512    182      2024-01-20    42   NaN   NaN     NaN   NaN   NaN   NaN    NaN
customer_id       4512    649          C10406    18   NaN   NaN     NaN   NaN   NaN   NaN    NaN
segment           4422      3        Consumer  2807   NaN   NaN     NaN   NaN   NaN   NaN    NaN
channel           4444      3          Online  2727   NaN   NaN     NaN   NaN   NaN   NaN    NaN
country           4512      6   United States  1708   NaN   NaN     NaN   NaN   NaN   NaN    NaN
city              4512     21        San Jose   357   NaN   NaN     NaN   NaN   NaN   NaN    NaN
region            4512      3   North America  2258   NaN   NaN     NaN   NaN   NaN   NaN    NaN
category          4512      9          Coffee  1260   NaN   NaN     NaN   NaN   NaN   NaN    NaN
product_name      4512     20  Espresso Blend   338   NaN   NaN     NaN   NaN   NaN   NaN    NaN
quantity      4,512.00    NaN             NaN   NaN  2.92  1.54   -2.00  2.00  3.00  4.00   5.00
unit_price    4,512.00    NaN             NaN   NaN 20.22 14.28    8.55 13.00 16.62 22.00  82.95
discount      4,512.00    NaN             NaN   NaN  0.02  0.04    0.00  0.00  0.00  0.00   0.15
shipping_cost 4,467.00    NaN             NaN   NaN  7.48  2.89    2.50  5.00  7.43  9.98  12.49
revenue       4,512.00    NaN             NaN   NaN 58.24 55.80 -165.90 27.00 47.02 72.00 414.75

## Understanding columns in context

Below is a helpful conceptual interpretation of the dataset:

- `order_id`: transaction/order identifier
- `order_date`: date of order
- `customer_id`: customer identifier
- `segment`: customer segment
- `channel`: sales channel
- `country`, `city`, `region`: location fields
- `category`, `product_name`: product hierarchy
- `quantity`: units sold, possibly negative for returns
- `unit_price`: price per unit
- `discount`: discount fraction
- `shipping_cost`: shipping cost
- `revenue`: transaction revenue after discount

### Questions
- Which columns describe **who** bought?
- Which columns describe **what** was bought?
- Which columns describe **where**?
- Which columns describe **money/value**?

## Selecting columns

Before we do complex analysis, we should be comfortable selecting columns in different ways.

In [ ]:
df["country"].head()

In [ ]:
df[["country", "city", "category", "revenue"]].head(10)

### Mini exercise

Create a smaller view of the data showing only:
- `order_date`
- `customer_id`
- `country`
- `category`
- `product_name`
- `quantity`
- `revenue`

Then display the first 8 rows.

In [ ]:
# Your code here
df[["order_date", "customer_id", "country", "category", "product_name", "quantity", "revenue"]].head(8)

## Frequency tables for categorical columns

In practical analytics work, a very fast way to understand a dataset is to ask:

- How many countries?
- Which channels appear most often?
- Which categories are most common?
- Which city values look suspicious?

The workhorse function here is:

```python
value_counts()
```

In [15]:
df["country"].value_counts()

country
United States     1708
United Kingdom     851
Germany            560
Canada             550
Australia          432
France             411
Name: count, dtype: int64

In [20]:
df["category"].value_counts(dropna=False) # NaN values are included in the count

category
Coffee       1260
Bakery        925
Equipment     827
Merch         784
Tea           706
merch           4
coffee          3
equipment       2
tea             1
Name: count, dtype: int64

In [22]:
df["channel"].value_counts(dropna=False, ascending=True)

channel
NaN               68
Store Pickup     807
Marketplace      910
Online          2727
Name: count, dtype: int64

In [21]:
df["city"].value_counts(dropna=False).head(15)

city
San Jose      357
Chicago       356
Seattle       344
New York      339
Austin        309
Manchester    290
London        289
Birmingham    270
Berlin        193
Vancouver     192
Montreal      184
Hamburg       184
Munich        182
Toronto       173
Paris         154
Name: count, dtype: int64

### Teaching moment

Notice that `value_counts(dropna=False)` includes missing values.  
This is extremely useful because missingness is itself information.

### Discussion prompts
- Do any category values look inconsistent?
- Do any city values look suspicious?
- Why might blank strings be a problem even if they are not `NaN`?

## Looking at unique values

Another useful exploration pattern:
- `nunique()` gives the number of distinct values
- `unique()` shows the actual distinct values, including missing value

These are especially useful for columns like category, segment, and channel.

In [23]:
df.nunique()

order_id         4500
order_date        182
customer_id       649
segment             3
channel             3
country             6
city               21
region              3
category            9
product_name       20
quantity            7
unit_price         54
discount            4
shipping_cost     997
revenue           485
dtype: int64

In [25]:
df["segment"].unique()

<StringArray>
['Consumer', 'Small Business', 'Corporate', nan]
Length: 4, dtype: str

In [26]:
df["category"].unique()

<StringArray>
['Merch', 'Bakery', 'Coffee', 'Tea', 'Equipment', 'coffee', 'merch', 'equipment', 'tea']
Length: 9, dtype: str

### Mini exercise

Check the unique values in:
- `channel`
- `region`
- `country`

Then write one sentence about what you learn from each.

In [27]:
print("channel:", df["channel"].unique())
print("region:", df["region"].unique())
print("country:", df["country"].unique())

channel: <StringArray>
['Online', 'Marketplace', 'Store Pickup', nan]
Length: 4, dtype: str
region: <StringArray>
['Europe', 'APAC', 'North America']
Length: 3, dtype: str
country: <StringArray>
['Germany', 'Australia', 'United States', 'France', 'United Kingdom', 'Canada']
Length: 6, dtype: str

## Inspecting numeric columns more thoughtfully

`describe()` is helpful, but analysts should also ask:
- Are there impossible values?
- Are there negative values?
- Are there zeros where zeros may be suspicious?
- Are some columns skewed?

Let's inspect a few key numeric columns.

In [28]:
df[["quantity", "unit_price", "discount", "shipping_cost", "revenue"]].describe().T

                 count  mean   std     min   25%   50%   75%    max
quantity      4,512.00  2.92  1.54   -2.00  2.00  3.00  4.00   5.00
unit_price    4,512.00 20.22 14.28    8.55 13.00 16.62 22.00  82.95
discount      4,512.00  0.02  0.04    0.00  0.00  0.00  0.00   0.15
shipping_cost 4,467.00  7.48  2.89    2.50  5.00  7.43  9.98  12.49
revenue       4,512.00 58.24 55.80 -165.90 27.00 47.02 72.00 414.75

In [34]:
(df["quantity"] < 0).sum() # Count of negative quantity values

np.int64(94)

### Question

We found transactions with negative quantity.  
In a real business setting, what might negative quantity mean?

Possible interpretations:
- returns
- refunds
- order corrections
- data entry errors

This is a great example of why data exploration comes **before** assumptions.

## Sorting data

Sorting helps students move from summary-level understanding to record-level inspection.

In [35]:
df.sort_values("revenue", ascending=False).head(10)

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
2541,O105051,2024-04-27,C10102,Corporate,Online,United Kingdom,Manchester,Europe,Equipment,Burr Grinder,5,82.95,0.00,11.59,414.75
2091,O104164,2024-05-07,C10132,Small Business,Store Pickup,Germany,Hamburg,Europe,Equipment,Burr Grinder,5,79.00,0.00,5.31,395.00
3197,O106332,2024-04-01,C10559,Consumer,Online,Australia,Melbourne,APAC,Equipment,Burr Grinder,5,79.00,0.00,3.81,395.00
2186,O104348,2024-05-30,C10138,Consumer,Marketplace,United States,Chicago,North America,Equipment,Burr Grinder,5,79.00,0.00,8.93,395.00
1941,O103851,2024-06-13,C10580,Consumer,Online,United Kingdom,Birmingham,Europe,Equipment,Burr Grinder,5,79.00,0.00,12.38,395.00
2009,O103995,2024-04-21,C10301,Consumer,Online,United Kingdom,Birmingham,Europe,Equipment,Burr Grinder,5,79.00,0.00,4.41,395.00
2526,O105025,2024-06-03,C10040,Consumer,Online,United States,Chicago,North America,Equipment,Burr Grinder,5,79.00,0.00,6.40,395.00
2505,O104985,2024-04-22,C10641,Consumer,Online,Australia,Melbourne,APAC,Equipment,Burr Grinder,5,79.00,0.00,7.10,395.00
3088,O106134,2024-02-25,C10048,Consumer,Online,United States,Chicago,North America,Equipment,Burr Grinder,5,79.00,0.00,9.13,395.00
4054,O108103,2024-01-28,C10252,Consumer,Online,United Kingdom,Birmingham,Europe,Equipment,Burr Grinder,5,79.00,0.00,9.54,395.00

In [36]:
df.sort_values("quantity").head(10)

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
3138,O106216,2024-02-09,C10296,Consumer,Online,United Kingdom,Birmingham,Europe,Merch,Tote Bag,-2,18.00,0.00,11.49,-36.00
3299,O106535,2024-03-16,C10135,NaN,NaN,United States,Austin,North America,Coffee,Cold Brew Pack,-2,14.00,0.00,NaN,-28.00
3280,O106497,2024-06-29,C10253,Small Business,Store Pickup,Germany,Munich,Europe,Equipment,Burr Grinder,-2,79.00,0.10,7.01,-142.20
2984,O105926,2024-02-19,C10189,Small Business,Online,United States,Seattle,North America,Merch,Ceramic Mug,-2,14.00,0.10,11.11,-25.20
3061,O106072,2024-02-27,C10254,Consumer,Online,Australia,Brisbane,APAC,Tea,Earl Grey,-2,11.00,0.00,3.70,-22.00
1045,O102064,2024-01-31,C10558,Consumer,Store Pickup,United Kingdom,Manchester,Europe,Merch,Travel Mug,-2,22.00,0.00,5.21,-44.00
3511,O106970,2024-01-02,C10372,Corporate,Store Pickup,France,Paris,Europe,Bakery,Cookie Pack,-2,9.00,0.00,6.59,-18.00
1209,O102384,2024-03-18,C10505,Consumer,Online,United States,San Jose,North America,Tea,Matcha Tin,-2,19.00,0.00,5.46,-38.00
3448,O106841,2024-05-24,C10089,Consumer,Online,Canada,Toronto,North America,Equipment,Burr Grinder,-2,82.95,0.00,12.37,-165.90
3531,O107014,2024-01-19,C10608,Consumer,Online,United States,Austin,North America,Coffee,Ethiopian Beans,-2,18.00,0.05,7.10,-34.20

### Questions

- What do the highest-revenue transactions look like?
- What do the lowest-quantity rows look like?
- Do the lowest-quantity rows suggest returns?

In [ ]:
# show all rows with the highest revenue
max_revenue = df["revenue"].max()
highest_revenue_all = df[df["revenue"] == max_revenue]

print(highest_revenue_all)

## Filtering rows

Filtering is one of the most important practical Pandas skills.

Examples:
- orders from the United States
- orders from Germany in the Equipment category
- orders with missing segment
- transactions with negative quantity
- high-revenue transactions

In [37]:
df[df["country"] == "United States"].head()

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
3,O100006,2024-01-18,C10309,Small Business,Store Pickup,United States,San Jose,North America,Coffee,Colombian Beans,4,16.50,0.00,6.87,66.00
8,O100015,2024-03-03,C10290,Consumer,Online,United States,Chicago,North America,Coffee,Espresso Blend,3,17.50,0.00,8.80,52.50
14,O100030,2024-01-26,C10472,Consumer,Online,United States,New York,North America,Tea,Herbal Tea,4,10.00,0.00,11.66,40.00
15,O100031,2024-04-07,C10619,Consumer,Store Pickup,United States,Seattle,North America,Bakery,Biscotti Jar,2,11.50,0.00,5.06,23.00
17,O100036,2024-05-11,C10156,Consumer,Online,United States,New York,North America,Coffee,Espresso Blend,5,18.38,0.05,4.03,87.28

In [38]:
df[(df["country"] == "Germany") & (df["category"].str.lower() == "equipment")].head()

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
5,O100011,2024-04-12,C10074,Consumer,Marketplace,Germany,Munich,Europe,Equipment,Pour Over Kit,2,34.00,0.00,8.15,68.00
129,O100234,2024-03-22,C10470,Small Business,Online,Germany,Hamburg,Europe,Equipment,Pour Over Kit,3,34.00,0.00,3.40,102.00
149,O100275,2024-04-25,C10120,Small Business,Store Pickup,Germany,Hamburg,Europe,Equipment,French Press,1,28.00,0.00,10.46,28.00
164,O100309,2024-03-25,C10056,Small Business,Online,Germany,Munich,Europe,Equipment,French Press,3,28.00,0.00,9.93,84.00
165,O100311,2024-03-15,C10603,Consumer,Marketplace,Germany,Hamburg,Europe,Equipment,Pour Over Kit,4,34.00,0.00,8.52,136.00

In [39]:
df[df["segment"].isna()].head()

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
23,O100046,2024-06-17,C10068,NaN,NaN,United States,Seattle,North America,Bakery,Croissant Box,5,15.00,0.00,3.96,75.00
151,O100280,2024-04-07,C10551,NaN,NaN,Germany,Berlin,Europe,Merch,Travel Mug,2,22.00,0.00,NaN,44.00
157,O100294,2024-04-09,C10487,NaN,NaN,United States,Chicago,North America,Merch,Ceramic Mug,2,13.30,0.05,9.96,25.27
199,O100385,2024-01-22,C10246,NaN,NaN,United Kingdom,London,Europe,Bakery,Cookie Pack,1,9.00,0.00,NaN,9.00
252,O100490,2024-05-18,C10087,NaN,NaN,United States,New York,North America,Equipment,Burr Grinder,3,79.00,0.00,8.88,237.00

In [40]:
df[df["quantity"] < 0].head(10)

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
24,O100049,2024-05-03,C10335,Consumer,Online,Australia,Melbourne,APAC,Tea,Green Tea,-1,12.00,0.00,4.25,-12.00
142,O100260,2024-04-26,C10310,Consumer,Online,Australia,Brisbane,APAC,Bakery,Cookie Pack,-2,8.55,0.00,6.57,-17.10
184,O100350,2024-05-22,C10063,Consumer,Online,Canada,Montreal,North America,Tea,Matcha Tin,-2,19.00,0.00,5.95,-38.00
213,O100407,2024-02-21,C10036,Consumer,Online,United States,New York,North America,Merch,Tote Bag,-2,17.10,0.05,4.85,-32.49
216,O100411,2024-05-16,C10218,Consumer,Store Pickup,United States,Austin,North America,Merch,Tote Bag,-1,18.00,0.00,10.12,-18.00
233,O100451,2024-02-17,C10362,Consumer,Online,United States,Seattle,North America,Coffee,Colombian Beans,-2,17.32,0.00,10.77,-34.65
261,O100508,2024-04-09,C10305,Consumer,Online,United States,Chicago,North America,Coffee,Ethiopian Beans,-2,18.00,0.00,3.44,-36.00
314,O100599,2024-03-28,C10187,Consumer,Online,United States,Chicago,North America,Bakery,Cookie Pack,-1,9.00,0.00,10.43,-9.00
345,O100661,2024-05-25,C10166,Corporate,Marketplace,United States,San Jose,North America,Coffee,Ethiopian Beans,-1,18.00,0.00,9.16,-18.00
413,O100796,2024-03-13,C10439,Small Business,Marketplace,Germany,Berlin,Europe,Tea,Green Tea,-1,12.00,0.00,9.96,-12.00

In [41]:
df[df["revenue"] > 150].head(10)

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
19,O100039,2024-01-15,C10522,Corporate,Online,United Kingdom,Birmingham,Europe,Equipment,Burr Grinder,5,79.00,0.00,3.81,395.00
22,O100045,2024-02-19,C10392,Small Business,Marketplace,United States,Seattle,North America,Equipment,Burr Grinder,4,79.00,0.00,6.76,316.00
25,O100050,2024-03-16,C10616,Consumer,Online,United States,Seattle,North America,Equipment,Burr Grinder,5,79.00,0.00,4.87,395.00
32,O100063,2024-01-22,C10510,Consumer,Store Pickup,United Kingdom,Manchester,Europe,Equipment,Burr Grinder,3,79.00,0.00,8.50,237.00
42,O100084,2024-01-22,C10084,Consumer,Online,United States,Chicago,North America,Equipment,Burr Grinder,4,79.00,0.00,7.58,316.00
70,O100133,2024-02-16,C10189,Small Business,Marketplace,United Kingdom,London,Europe,Equipment,Burr Grinder,5,75.05,0.00,4.13,375.25
96,O100176,2024-03-13,C10337,Corporate,Online,United States,Chicago,North America,Equipment,Burr Grinder,4,82.95,0.00,8.75,331.80
109,O100200,2024-03-17,C10187,Consumer,Online,United Kingdom,Birmingham,Europe,Equipment,Pour Over Kit,5,34.00,0.00,8.52,170.00
135,O100245,2024-04-26,C10296,Consumer,Marketplace,Australia,Sydney,APAC,Equipment,Pour Over Kit,5,34.00,0.05,8.98,161.50
239,O100464,2024-06-29,C10301,Small Business,Marketplace,France,Lyon,Europe,Equipment,Burr Grinder,2,79.00,0.05,4.48,150.10

### Mini exercise

Write filters to answer the following:
1. Show all rows from `Canada`
2. Show all rows where `category` is `Coffee`
3. Show all rows where `revenue` is greater than 100
4. Show all rows where `shipping_cost` is missing

In [42]:
# 1
df[df["country"] == "Canada"].head()

# 2
df[df["category"].str.lower() == "coffee"].head()

# 3
df[df["revenue"] > 100].head()

# 4
df[df["shipping_cost"].isna()].head()

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
151,O100280,2024-04-07,C10551,NaN,NaN,Germany,Berlin,Europe,Merch,Travel Mug,2,22.00,0.00,NaN,44.00
199,O100385,2024-01-22,C10246,NaN,NaN,United Kingdom,London,Europe,Bakery,Cookie Pack,1,9.00,0.00,NaN,9.00
416,O100803,2024-06-07,C10499,NaN,NaN,Germany,Hamburg,Europe,Merch,T-Shirt,3,26.00,0.10,NaN,70.20
443,O100860,2024-03-12,C10547,NaN,NaN,United States,Seattle,North America,Coffee,Cold Brew Pack,3,14.00,0.05,NaN,39.90
468,O100911,2024-03-16,C10564,NaN,NaN,United States,Seattle,North America,Coffee,Colombian Beans,2,16.50,0.00,NaN,33.00

## 13. Business question 1: Which countries generate the most revenue?

This is the first time we move from "understanding the file" to "answering a decision-relevant question."

For now, we will use a very simple aggregation.

In [ ]:
df.groupby("country", dropna=False)["revenue"].sum().sort_values(ascending=False)

### Discussion prompts
- Which country generates the most revenue?
- Is that because of larger order sizes, more transactions, or both?
- What follow-up analysis would management want next?

## Business question: Which categories appear most often?

This is not the same as highest revenue.  
Frequency and value are different.

A category might appear often but generate lower revenue per transaction.

In [43]:
df["category"].value_counts(dropna=False)

category
Coffee       1260
Bakery        925
Equipment     827
Merch         784
Tea           706
merch           4
coffee          3
equipment       2
tea             1
Name: count, dtype: int64

In [44]:
df.groupby("category", dropna=False)["revenue"].sum().sort_values(ascending=False)

category
Equipment   99,456.91
Coffee      59,829.71
Merch       44,288.48
Bakery      32,393.15
Tea         26,246.29
equipment      332.76
coffee         125.60
merch          115.10
tea             12.00
Name: revenue, dtype: float64

### Question

Compare:
- category frequency
- category revenue

Do the rankings match? If not, what might explain the difference?

## Business question: Which channels seem strongest?

Channels matter for operational strategy, cost structure, and customer experience.

In [45]:
df["channel"].value_counts(dropna=False)

channel
Online          2727
Marketplace      910
Store Pickup     807
NaN               68
Name: count, dtype: int64

In [ ]:
df.groupby("channel", dropna=False)["revenue"].agg(["count", "sum", "mean"]).sort_values("sum", ascending=False)

### Question

What is the difference between:
- number of transactions (`count`)
- total revenue (`sum`)
- average revenue per transaction (`mean`)

## Business question: Which cities generate the most revenue?

This is often the kind of question regional managers ask first.

In [ ]:
df.groupby("city", dropna=False)["revenue"].sum().sort_values(ascending=False).head(15)

### Question

Do any values in the city summary look suspicious or messy?

Hint:
- blank strings
- inconsistent values
- missing or malformed location data

## Checking data quality during exploration

Exploration and quality review should happen together.

Students should get into the habit of checking:
- missing values
- duplicates
- odd values
- inconsistent text
- unexpected categories

In [46]:
df.isna().sum().sort_values(ascending=False)

segment          90
channel          68
shipping_cost    45
customer_id       0
order_date        0
country           0
order_id          0
city              0
region            0
product_name      0
category          0
quantity          0
unit_price        0
discount          0
revenue           0
dtype: int64

In [47]:
df.duplicated().sum()

np.int64(12)

In [48]:
df[df.duplicated()].head()

,order_id,order_date,customer_id,segment,channel,country,city,region,category,product_name,quantity,unit_price,discount,shipping_cost,revenue
4500,O100695,2024-01-14,C10375,Consumer,Online,United States,Seattle,North America,Equipment,Burr Grinder,1,79.00,0.10,3.95,71.10
4501,O104021,2024-05-05,C10478,Consumer,Online,Germany,Munich,Europe,Bakery,Biscotti Jar,5,12.08,0.00,6.54,60.38
4502,O100921,2024-02-12,C10059,Consumer,Online,United States,San Jose,North America,Equipment,Milk Frother,1,24.00,0.00,3.88,24.00
4503,O104352,2024-04-10,C10058,Consumer,Online,France,Paris,Europe,Coffee,Ethiopian Beans,4,18.00,0.00,10.72,72.00
4504,O102476,2024-01-14,C10490,Consumer,Online,France,Lyon,Europe,Equipment,Milk Frother,2,24.00,0.00,6.41,48.00

### Question

If duplicate rows appear in a transaction dataset, what could that mean?

Possible explanations:
- accidental duplicate records
- duplicate extraction from a source system
- legitimate repeated purchases that only look duplicated
- data integration issues

A careful analyst does not delete rows blindly.

## A closer look at dates

Dates are crucial in real analytics work.

Even in an exploration session, students should check:
- Is the date column stored as text or actual datetime?
- What is the date range?
- Are there obvious gaps or impossible values?

In [49]:
df["order_date"].head()

0    2024-04-01
1    2024-05-07
2    2024-03-15
3    2024-01-18
4    2024-03-26
Name: order_date, dtype: str

In [50]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["order_date"].dtype

dtype('<M8[us]')

In [51]:
df["order_date"].min(), df["order_date"].max()

(Timestamp('2024-01-01 00:00:00'), Timestamp('2024-06-30 00:00:00'))

In [52]:
df["order_month"] = df["order_date"].dt.to_period("M")
df[["order_date", "order_month"]].head()

  order_date order_month
0 2024-04-01     2024-04
1 2024-05-07     2024-05
2 2024-03-15     2024-03
3 2024-01-18     2024-01
4 2024-03-26     2024-03

### Future advanced topics
- feature engineering
- time series
- monthly aggregation

## Quick monthly revenue view

This is still exploration, not yet full time-series analysis.

In [53]:
df.groupby("order_month")["revenue"].sum()

order_month
2024-01   46,650.18
2024-02   41,487.72
2024-03   44,996.34
2024-04   41,912.66
2024-05   44,181.04
2024-06   43,572.06
Freq: M, Name: revenue, dtype: float64

### Questions

What could explain month-to-month changes in revenue?
- seasonality
- growth
- promotions
- incomplete data
- returns

## Customer-level exploration

A common analytics question is whether revenue comes from many small customers or a few large ones.

In [54]:
customer_summary = (
    df.groupby("customer_id")
      .agg(
          transactions=("order_id", "count"),
          total_revenue=("revenue", "sum"),
          avg_revenue=("revenue", "mean")
      )
      .sort_values("total_revenue", ascending=False)
)

customer_summary.head(10)

             transactions  total_revenue  avg_revenue
customer_id
C10624                 18       1,752.32        97.35
C10048                 16       1,329.64        83.10
C10544                 12       1,223.78       101.98
C10308                 16       1,205.73        75.36
C10327                 12       1,176.15        98.01
C10426                 17       1,078.70        63.45
C10267                 10       1,077.58       107.76
C10072                 14       1,067.10        76.22
C10543                 12       1,038.40        86.53
C10406                 18       1,037.91        57.66

### Question

What would leadership want to know next about top customers?
- country?
- segment?
- product preferences?
- retention over time?

## Guided lab: students explore independently

Use the next block as a structured in-class lab.  
Students should work individually 

### Task set A — Basic structure
1. How many rows and columns are in the dataset?
2. Which columns have missing values?
3. Which columns are numeric?
4. Which columns are categorical?

### Task set B — Business understanding
5. Which country has the most transactions?
6. Which category has the highest total revenue?
7. Which channel has the highest average revenue per transaction?
8. Which city appears most often?

### Task set C — Quality review
9. Are there duplicate rows?
10. Are there negative quantities?
11. Are there inconsistent category values?
12. Are there blank-like city values?

Write short answers in markdown cells after each code block.

In [58]:
# Add your code below

## Solution sketch for guided lab

Use or reveal this section only after students attempt the guided lab.

In [55]:
print("Rows, Columns:", df.shape)
print("\nMissing values:")
print(df.isna().sum())
print("\nNumeric columns:")
print(df.select_dtypes(include=np.number).columns.tolist())
print("\nCategorical/object columns:")
print(df.select_dtypes(exclude=np.number).columns.tolist())

Rows, Columns: (4512, 16)

Missing values:
order_id          0
order_date        0
customer_id       0
segment          90
channel          68
country           0
city              0
region            0
category          0
product_name      0
quantity          0
unit_price        0
discount          0
shipping_cost    45
revenue           0
order_month       0
dtype: int64

Numeric columns:
['quantity', 'unit_price', 'discount', 'shipping_cost', 'revenue']

Categorical/object columns:
['order_id', 'order_date', 'customer_id', 'segment', 'channel', 'country', 'city', 'region', 'category', 'product_name', 'order_month']

In [59]:
print("Country with most transactions:")
print(df["country"].value_counts().head(1))

print("\nCategory with highest total revenue:")
print(df.groupby("category")["revenue"].sum().sort_values(ascending=False).head(1))

print("\nChannel with highest average revenue:")
print(df.groupby("channel")["revenue"].mean().sort_values(ascending=False).head(1))

print("\nMost common city:")
print(df["city"].value_counts(dropna=False).head(5))

Country with most transactions:
country
United States    1708
Name: count, dtype: int64

Category with highest total revenue:
category
Equipment   99,456.91
Name: revenue, dtype: float64

Channel with highest average revenue:
channel
Online   59.25
Name: revenue, dtype: float64

Most common city:
city
San Jose    357
Chicago     356
Seattle     344
New York    339
Austin      309
Name: count, dtype: int64

In [57]:
print("Duplicate rows:", df.duplicated().sum())
print("Negative quantities:", (df["quantity"] < 0).sum())
print("\nUnique category values:")
print(df["category"].unique())
print("\nBlank-like city rows:")
print((df["city"].astype(str).str.strip() == "").sum())

Duplicate rows: 12
Negative quantities: 94

Unique category values:
<StringArray>
['Merch', 'Bakery', 'Coffee', 'Tea', 'Equipment', 'coffee', 'merch', 'equipment', 'tea']
Length: 9, dtype: str

Blank-like city rows:
8

## Challenge case: analyst memo for management

Imagine your manager asks for a quick exploratory summary after your first hour with the dataset.

Write a short memo with:
1. two useful observations
2. two data quality concerns
3. two follow-up questions you would investigate next

This is a good chance to practice **business communication**, not just coding.

### Example memo template

> **Initial observations**
> - ...
> - ...
>
> **Data concerns**
> - ...
> - ...
>
> **Next questions**
> - ...
> - ...

## More challenging questions

- Find the top 10 products by total revenue.
- Find the top 5 customers in each country by total revenue.
- Compare average discount by category.
- Create a table showing transaction count, total revenue, and average revenue by:
    - country
    - channel
    - category
- Investigate whether negative quantity rows have negative revenue too.
- Find rows where the city looks blank or malformed.

In [ ]:
# Q1
df.groupby("product_name")["revenue"].sum().sort_values(ascending=False).head(10)

In [ ]:
# Q2
top_customers_by_country = (
    df.groupby(["country", "customer_id"])["revenue"]
      .sum()
      .reset_index()
      .sort_values(["country", "revenue"], ascending=[True, False])
)

top_customers_by_country.groupby("country").head(5)

In [ ]:
# Q3
df.groupby("category")["discount"].mean().sort_values(ascending=False)

In [60]:
# Q4
df.groupby(["country", "channel", "category"])["revenue"].agg(["count", "sum", "mean"]).head(20)

                                  count      sum   mean
country   channel      category
Australia Marketplace  Bakery        12   460.26  38.35
                       Coffee        21   789.37  37.59
                       Equipment     11 1,434.15 130.38
                       Merch         13   874.76  67.29
                       Tea           16   579.97  36.25
          Online       Bakery        45 1,434.06  31.87
                       Coffee        75 3,392.99  45.24
                       Equipment     57 7,221.44 126.69
                       Merch         46 2,635.59  57.30
                       Tea           47 1,849.16  39.34
          Store Pickup Bakery        11   332.53  30.23
                       Coffee        26 1,380.39  53.09
                       Equipment     13 1,597.00 122.85
                       Merch         13   567.20  43.63
                       Tea           16   735.69  45.98
                       equipment      1   237.00 237.00
                       merch          1   -11.90 -11.90
Canada    Marketplace  Bakery        23   844.75  36.73
                       Coffee        21   749.72  35.70
                       Equipment     22 2,581.99 117.36

In [61]:
# Q5
df.loc[df["quantity"] < 0, ["order_id", "quantity", "revenue"]].head(20)

     order_id  quantity  revenue
24    O100049        -1   -12.00
142   O100260        -2   -17.10
184   O100350        -2   -38.00
213   O100407        -2   -32.49
216   O100411        -1   -18.00
233   O100451        -2   -34.65
261   O100508        -2   -36.00
314   O100599        -1    -9.00
345   O100661        -1   -18.00
413   O100796        -1   -12.00
421   O100811        -1   -17.50
641   O101265        -1   -34.00
930   O101840        -1   -12.00
1027  O102031        -1   -34.00
1044  O102063        -1   -15.30
1045  O102064        -2   -44.00
1169  O102302        -1   -18.90
1209  O102384        -2   -38.00
1292  O102544        -2   -52.00
1294  O102550        -1   -79.00

In [62]:
# Q6
df[df["city"].astype(str).str.strip() == ""][["order_id", "country", "city", "revenue"]].head()

     order_id         country city  revenue
57    O100111  United Kingdom         45.00
753   O101490   United States         72.00
1763  O103500          France         14.00
1885  O103742  United Kingdom         68.00
2820  O105595          Canada         32.78

## Reflection questions

These work well as end-of-session discussion prompts or a short written reflection.

1. Which Pandas commands felt most useful today?
2. What did you learn from `info()` that was not obvious from `head()`?
3. Why is it dangerous to begin modeling before exploring the data?
4. What data quality issues did you identify?
5. What additional variables would you want if you were advising management?