# Pandas Case Study: Employee Attrition Data Exploration

## Case context

You are working as a junior data analyst for the HR analytics team. The company wants to better understand employee attrition before building dashboards or predictive models.

The goal of this notebook is **not visualization** and **not machine learning**. The goal is to demonstrate a practical data exploration process using pandas.

## What students will practice

This notebook reviews the major pandas concepts covered in the module:

- loading a real dataset
- inspecting rows, columns, data types, and summary statistics
- using `describe()` for numerical and categorical variables
- checking duplicates and missing values
- creating new columns
- cleaning and standardizing values
- using `loc` and `iloc`
- filtering and sorting
- using `lambda`
- using `apply()` with custom functions
- using `groupby()` and `agg()`
- using `transform()` to compare employees with their group average
- building reusable exploration tables

Dataset: IBM HR Analytics Employee Attrition dataset. The dataset is commonly used for HR analytics practice and is available through public GitHub mirrors of the Kaggle dataset.

## 1. Import libraries and configure pandas

**Task:** Import the libraries needed for data exploration.

**Goal:** Make the notebook easier to read by showing more columns and formatting numerical output.

In [6]:
import pandas as pd
import numpy as np

# Display more columns so students can inspect the full dataset.
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 120)

# Format floats to two decimal places for cleaner summary tables.
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

## 2. Load the dataset

**Task:** Load the employee attrition dataset from a public CSV URL.

**Goal:** Start with a real dataset and keep a copy of the raw data in case we need to compare before and after cleaning.

In [7]:
# url = "https://raw.githubusercontent.com/mrc03/IBM-HR-Analytics-Employee-Attrition-Performance/master/WA_Fn-UseC_-HR-Employee-Attrition.csv"

df = pd.read_csv('practice_employee_attrition.csv')

# Keep a copy of the original dataset.
raw_df = df.copy()

print("Rows and columns:", df.shape)
df.head(2)

Rows and columns: (1470, 32)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4.00,Single,"5,993.00",19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,Male,61,2,2,Research Scientist,2.00,Married,"5,130.00",24907,1,No,23,4,4,1,10,3,3,10,7,1,7

## 3. First look at the data

**Business questions:**

1. How many employee records are in the dataset?
2. What columns are available?
3. What does one employee record look like?
4. Which columns are numerical and which are categorical?

**Pandas concepts:** `head()`, `tail()`, `sample()`, `columns`, `info()`.

In [8]:
# First five rows
# Good for quickly seeing column names and example values.
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4.00,Single,"5,993.00",19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,Male,61,2,2,Research Scientist,2.00,Married,"5,130.00",24907,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,Male,92,2,1,Laboratory Technician,3.00,Single,"2,090.00",2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,Female,56,3,1,Research Scientist,3.00,Married,"2,909.00",23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,Male,40,3,1,Laboratory Technician,2.00,Married,"3,468.00",16632,9,No,12,3,4,1,6,3,3,2,2,2,2

In [9]:
# Last five rows
# Useful for checking whether the file has unusual ending rows.
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,2061,3,Male,41,4,2,Laboratory Technician,4.00,Married,"2,571.00",12290,4,No,17,3,3,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,2062,4,Male,42,2,3,Healthcare Representative,1.00,Married,"9,991.00",21457,4,No,15,3,1,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2064,2,Male,87,4,2,Manufacturing Director,2.00,Married,"6,142.00",5174,1,Yes,20,4,2,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,2065,4,Male,63,2,2,Sales Executive,2.00,Married,"5,390.00",13243,2,No,14,3,4,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,2068,2,Male,82,4,2,Laboratory Technician,3.00,Married,"4,404.00",10228,2,No,12,3,1,0,6,3,4,4,3,1,2

In [10]:
# Random rows
# This often gives a more representative quick view than only using head().
df.sample(5, random_state=42)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1041,28,No,Travel_Rarely,866,Sales,5,3,Medical,1469,4,Male,84,3,2,Sales Executive,1.00,Single,"8,463.00",23490,0,No,18,3,4,0,6,4,3,5,4,1,3
184,53,No,Travel_Rarely,1084,Research & Development,13,2,Medical,250,4,Female,57,4,2,Manufacturing Director,1.00,Divorced,NaN,26250,1,No,11,3,3,2,5,3,3,4,2,1,3
1222,24,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1714,4,Male,58,1,1,Human Resources,3.00,Married,"1,555.00",11585,1,No,11,3,3,1,1,2,3,1,0,0,0
67,45,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,86,2,Male,59,3,3,Research Scientist,1.00,Divorced,"9,724.00",18787,2,No,17,3,3,1,25,2,3,1,0,0,0
220,36,No,Travel_Rarely,1396,Research & Development,5,2,Life Sciences,304,4,Male,62,3,2,Laboratory Technician,2.00,Single,"5,914.00",9945,8,No,16,3,4,0,16,3,4,13,11,3,7

In [11]:
# List all column names.
list(df.columns)

['Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [12]:
# Data types and non-null counts.
# This is one of the most important first steps in any pandas project.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1456 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   str
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   str
 15  JobSatisfaction           1441 non-null   float64
 16  MaritalStatus             1470 non-null   str
 17  MonthlyIncome             1426 non-null   float64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  OverTime                  1470 non-null   str
 21  PercentSalaryHike         1470 non-null   int64
 22  PerformanceRating         1470 non-null   int64
 23  RelationshipSatisfaction  1470 non-null   int64
 24  StockOptionLevel          1470 non-null   int64
 25  TotalWorkingYears         1470 non-null   int64
 26  TrainingTimesLastYear     1470 non-null   int64
 27  WorkLifeBalance           1470 non-null   int64
 28  YearsAtCompany            1470 non-null   int64
 29  YearsInCurrentRole        1470 non-null   int64
 30  YearsSinceLastPromotion   1470 non-null   int64
 31  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(2), int64(22), str(8)
memory usage: 367.6 KB

## 4. Understand numerical and categorical variables

**Task:** Separate numerical and categorical columns.

**Goal:** Different types of columns need different exploration methods.

- Numerical columns can use mean, median, min, max, standard deviation.
- Categorical columns can use counts, unique values, and frequency tables.

In [14]:
numeric_cols = df.select_dtypes(include="number").columns.tolist()
categorical_cols = df.select_dtypes(include="object").columns.tolist()

print("Number of numerical columns:", len(numeric_cols))
print(numeric_cols)

print("Number of categorical columns:", len(categorical_cols))
print(categorical_cols)

Number of numerical columns: 24
['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']
Number of categorical columns: 8
['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

C:\Users\hlu\AppData\Local\Temp\ipykernel_9456\2785457986.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns.tolist()

In [ ]:
# Summary statistics for numerical variables.
# .T transposes the output so it is easier to read when there are many columns.
df.describe().T

In [15]:
# Summary statistics for categorical variables.
# count = non-missing values
# unique = number of distinct categories
# top = most frequent category
# freq = frequency of the most frequent category
df.describe(include="object").T

C:\Users\hlu\AppData\Local\Temp\ipykernel_9456\184190883.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object").T

               count unique                     top  freq
Attrition       1470      2                      No  1233
BusinessTravel  1456      3           Travel_Rarely  1032
Department      1470      3  Research & Development   961
EducationField  1470      6           Life Sciences   606
Gender          1470      2                    Male   882
JobRole         1470      9         Sales Executive   326
MaritalStatus   1470      3                 Married   673
OverTime        1470      2                      No  1054

## 5. Check duplicate rows and constant columns

**Business question:** Are there duplicated records or columns that contain no useful variation?

**Goal:** Identify data quality issues before deeper analysis.

A constant column has the same value for every row. It is usually not useful for analysis.

In [16]:
# Count duplicated rows.
duplicate_count = df.duplicated().sum()
print("Number of duplicated rows:", duplicate_count)

Number of duplicated rows: 0

In [17]:
# Find columns with only one unique value.
# nunique(dropna=False) counts missing as a distinct value if present.
unique_counts = df.nunique(dropna=False).sort_values()
constant_cols = unique_counts[unique_counts == 1]

constant_cols

Series([], dtype: int64)

In [18]:
# Inspect constant columns.
# These columns do not help explain differences among employees.
for col in constant_cols.index:
    print(f"{col}: {df[col].unique()}")

In [19]:
# Create a working dataframe that drops constant columns.
# In a real project, we would document why these columns are removed.
df_work = df.drop(columns=constant_cols.index)

print("Original shape:", df.shape)
print("Working shape after dropping constant columns:", df_work.shape)

Original shape: (1470, 32)
Working shape after dropping constant columns: (1470, 32)

## 6. Check missing values

**Business question:** Is the dataset complete enough for analysis?

**Goal:** Learn a standard missing-value inspection workflow.

The original dataset is very clean, so later we will intentionally create a few missing values for practice.

In [20]:
# Count missing values in each column.
missing_count = df_work.isna().sum().sort_values(ascending=False)
missing_percent = (df_work.isna().mean() * 100).sort_values(ascending=False)

missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percent": missing_percent
})

missing_summary.head(10)

                  missing_count  missing_percent
MonthlyIncome                44             2.99
JobSatisfaction              29             1.97
BusinessTravel               14             0.95
Attrition                     0             0.00
Department                    0             0.00
DistanceFromHome              0             0.00
Education                     0             0.00
Age                           0             0.00
EducationField                0             0.00
EmployeeNumber                0             0.00

In [21]:
# Show only columns with missing values.
missing_summary[missing_summary["missing_count"] > 0]

                 missing_count  missing_percent
MonthlyIncome               44             2.99
JobSatisfaction             29             1.97
BusinessTravel              14             0.95

## 7. Create missing values for teaching practice

**Task:** The original dataset has no major missing-value problem. To practice missing-value handling, create a teaching copy with artificial missing values.

**Goal:** Practice realistic cleaning strategies:

- fill numerical missing values with group median
- fill categorical missing values with a placeholder such as `Unknown`
- verify that missing values were handled correctly

This section is for teaching only. In a real analysis, you should not randomly create missing values.

In [22]:
practice_df = df_work.copy()

# Use a fixed random seed so everyone gets the same missing values.
rng = np.random.default_rng(seed=42)

# Randomly set about 3% of MonthlyIncome values to missing.
income_missing_index = rng.choice(practice_df.index, size=int(0.03 * len(practice_df)), replace=False)
practice_df.loc[income_missing_index, "MonthlyIncome"] = np.nan

# Randomly set about 2% of JobSatisfaction values to missing.
satisfaction_missing_index = rng.choice(practice_df.index, size=int(0.02 * len(practice_df)), replace=False)
practice_df.loc[satisfaction_missing_index, "JobSatisfaction"] = np.nan

# Randomly set about 1% of BusinessTravel values to missing.
travel_missing_index = rng.choice(practice_df.index, size=int(0.01 * len(practice_df)), replace=False)
practice_df.loc[travel_missing_index, "BusinessTravel"] = np.nan

practice_df[["Department", "MonthlyIncome", "JobSatisfaction", "BusinessTravel"]].isna().sum()

Department          0
MonthlyIncome      44
JobSatisfaction    29
BusinessTravel     14
dtype: int64

## 8. Handle missing values

**Task:** Fill the artificial missing values using reasonable rules.

**Business logic:**

- Monthly income varies by department, so fill missing income using the **department median**.
- Job satisfaction is an ordinal score, so fill missing values using the overall median.
- Business travel is categorical, so fill missing values with `Unknown`.

**Pandas concepts:** `groupby()`, `transform()`, `lambda`, `fillna()`.

In [23]:
# Before cleaning, inspect rows where MonthlyIncome is missing.
practice_df.loc[practice_df["MonthlyIncome"].isna(), ["Department", "JobRole", "MonthlyIncome"]].head()

                 Department                    JobRole  MonthlyIncome
93   Research & Development  Healthcare Representative            NaN
123  Research & Development          Research Director            NaN
127                   Sales       Sales Representative            NaN
134         Human Resources            Human Resources            NaN
135  Research & Development     Manufacturing Director            NaN

In [24]:
# Fill MonthlyIncome with the median MonthlyIncome within each Department.
practice_df["MonthlyIncome"] = practice_df.groupby("Department")["MonthlyIncome"].transform(
    lambda income_series: income_series.fillna(income_series.median())
)

# Fill JobSatisfaction with the overall median.
practice_df["JobSatisfaction"] = practice_df["JobSatisfaction"].fillna(practice_df["JobSatisfaction"].median())

# Fill missing BusinessTravel values with Unknown.
practice_df["BusinessTravel"] = practice_df["BusinessTravel"].fillna("Unknown")

# Verify remaining missing values.
practice_df[["MonthlyIncome", "JobSatisfaction", "BusinessTravel"]].isna().sum()

MonthlyIncome      0
JobSatisfaction    0
BusinessTravel     0
dtype: int64

In [25]:
# Continue the analysis with the cleaned practice dataframe.
df_clean = practice_df.copy()

print("Cleaned dataframe shape:", df_clean.shape)
df_clean.head()

Cleaned dataframe shape: (1470, 32)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4.00,Single,"5,993.00",19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,Male,61,2,2,Research Scientist,2.00,Married,"5,130.00",24907,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,Male,92,2,1,Laboratory Technician,3.00,Single,"2,090.00",2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,Female,56,3,1,Research Scientist,3.00,Married,"2,909.00",23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,Male,40,3,1,Laboratory Technician,2.00,Married,"3,468.00",16632,9,No,12,3,4,1,6,3,3,2,2,2,2

## 9. Create a target variable for analysis

**Business question:** Which employees left the company?

The original column `Attrition` contains `Yes` and `No`. For analysis, it is convenient to create a numerical column:

- `1` means the employee left
- `0` means the employee stayed

**Pandas concepts:** `map()`, value counts, percentages.

In [26]:
df_clean["AttritionFlag"] = df_clean["Attrition"].map({"Yes": 1, "No": 0})

# Count and percentage of attrition.
attrition_counts = df_clean["Attrition"].value_counts()
attrition_percent = df_clean["Attrition"].value_counts(normalize=True) * 100

pd.DataFrame({
    "count": attrition_counts,
    "percent": attrition_percent.round(2)
})

           count  percent
Attrition
No          1233    83.88
Yes          237    16.12

## 10. Use `loc` and `iloc` for row and column selection

**Task:** Practice selecting rows and columns by label and by position.

**Goal:** Understand when to use `loc` vs. `iloc`.

- `loc` selects by row labels and column names.
- `iloc` selects by integer position.

In [27]:
# Use loc to select employees who left and show selected columns.
df_clean.loc[df_clean["Attrition"] == "Yes", ["Age", "Department", "JobRole", "MonthlyIncome", "Attrition"]].head(10)

    Age              Department                JobRole  MonthlyIncome Attrition
0    41                   Sales        Sales Executive       5,993.00       Yes
2    37  Research & Development  Laboratory Technician       2,090.00       Yes
14   28  Research & Development  Laboratory Technician       2,028.00       Yes
21   36                   Sales   Sales Representative       3,407.00       Yes
24   34  Research & Development     Research Scientist       2,960.00       Yes
26   32  Research & Development     Research Scientist       3,919.00       Yes
33   39                   Sales   Sales Representative       2,086.00       Yes
34   24  Research & Development     Research Scientist       2,293.00       Yes
36   50                   Sales   Sales Representative       2,683.00       Yes
42   26  Research & Development  Laboratory Technician       2,293.00       Yes

In [28]:
# Use iloc to select the first 5 rows and first 6 columns by position.
df_clean.iloc[:5, :6]

   Age Attrition     BusinessTravel  DailyRate              Department  DistanceFromHome
0   41       Yes      Travel_Rarely       1102                   Sales                 1
1   49        No  Travel_Frequently        279  Research & Development                 8
2   37       Yes      Travel_Rarely       1373  Research & Development                 2
3   33        No  Travel_Frequently       1392  Research & Development                 3
4   27        No      Travel_Rarely        591  Research & Development                 2

In [29]:
# Combine a condition with loc to inspect high-income employees who left.
df_clean.loc[
    (df_clean["Attrition"] == "Yes") & (df_clean["MonthlyIncome"] > 10000),
    ["Age", "Department", "JobRole", "MonthlyIncome", "YearsAtCompany", "Attrition"]
].head(10)

     Age              Department                    JobRole  MonthlyIncome  YearsAtCompany Attrition
45    41  Research & Development          Research Director      19,545.00              22       Yes
126   58  Research & Development  Healthcare Representative      10,312.00              40       Yes
136   51  Research & Development     Manufacturing Director      10,650.00               4       Yes
210   32                   Sales            Sales Executive      10,400.00              14       Yes
250   37  Research & Development     Manufacturing Director      10,048.00               1       Yes
271   47  Research & Development                    Manager      11,849.00              10       Yes
435   33  Research & Development                    Manager      13,610.00               7       Yes
568   55  Research & Development                    Manager      19,859.00               5       Yes
595   58  Research & Development          Research Director      19,246.00              31       Yes
693   36                   Sales            Sales Executive      10,325.00              16       Yes

## 11. Create new columns for easier analysis

**Business question:** Can we convert raw columns into more useful business categories?

**Task:** Create several new columns:

1. `IncomeK`: monthly income in thousands
2. `OvertimeFlag`: numerical version of overtime
3. `YoungEmployee`: whether age is below 30
4. `LongTenure`: whether employee has worked at the company for at least 10 years
5. `IncomePerYearAtCompany`: income divided by years at company, with special handling for zero years

**Pandas concepts:** column arithmetic, `np.where()`, boolean conditions.

In [30]:
df_clean["IncomeK"] = df_clean["MonthlyIncome"] / 1000

df_clean["OvertimeFlag"] = df_clean["OverTime"].map({"Yes": 1, "No": 0})

df_clean["YoungEmployee"] = np.where(df_clean["Age"] < 30, "Yes", "No")

df_clean["LongTenure"] = np.where(df_clean["YearsAtCompany"] >= 10, "Yes", "No")

# Avoid division by zero when YearsAtCompany is 0.
df_clean["IncomePerYearAtCompany"] = np.where(
    df_clean["YearsAtCompany"] == 0,
    np.nan,
    df_clean["MonthlyIncome"] / df_clean["YearsAtCompany"]
)

df_clean[["Age", "MonthlyIncome", "IncomeK", "OverTime", "OvertimeFlag", "YoungEmployee", "LongTenure", "IncomePerYearAtCompany"]].head(10)

   Age  MonthlyIncome  IncomeK OverTime  OvertimeFlag YoungEmployee LongTenure  IncomePerYearAtCompany
0   41       5,993.00     5.99      Yes             1            No         No                  998.83
1   49       5,130.00     5.13       No             0            No        Yes                  513.00
2   37       2,090.00     2.09      Yes             1            No         No                     NaN
3   33       2,909.00     2.91      Yes             1            No         No                  363.62
4   27       3,468.00     3.47       No             0           Yes         No                1,734.00
5   32       3,068.00     3.07       No             0            No         No                  438.29
6   59       2,670.00     2.67      Yes             1            No         No                2,670.00
7   30       2,693.00     2.69       No             0            No         No                2,693.00
8   38       9,526.00     9.53       No             0            No         No                1,058.44
9   36       5,237.00     5.24       No             0            No         No                  748.14

## 12. Create categories using a custom function and `apply()`

**Business question:** Can we create a simple employee life-stage category based on age?

**Task:** Write a function that assigns employees into age bands.

**Pandas concepts:** custom function, `apply()`.

In [31]:
def assign_age_group(age):
    """Return an age group label based on employee age."""
    if age < 30:
        return "Under 30"
    elif age < 40:
        return "30-39"
    elif age < 50:
        return "40-49"
    else:
        return "50+"

# Apply the function to the Age column.
df_clean["AgeGroup"] = df_clean["Age"].apply(assign_age_group)

df_clean[["Age", "AgeGroup"]].head(10)

   Age  AgeGroup
0   41     40-49
1   49     40-49
2   37     30-39
3   33     30-39
4   27  Under 30
5   32     30-39
6   59       50+
7   30     30-39
8   38     30-39
9   36     30-39

## 13. Create a risk segment using row-wise `apply()`

**Business question:** Which employees might deserve closer HR attention based on simple business rules?

**Task:** Create a rule-based `RetentionRiskSegment` using multiple columns.

Example business rules:

- High Risk: employee works overtime and has low job satisfaction
- High Risk: employee is young, works overtime, and has low income
- Medium Risk: employee has low environment satisfaction or low work-life balance
- Low Risk: otherwise

This is not a predictive model. It is a transparent business-rule exercise for pandas practice.

**Pandas concepts:** row-wise `apply(axis=1)`, custom function, multiple conditions.

In [32]:
def assign_retention_risk(row):
    """Assign a simple rule-based retention risk segment."""
    if row["OverTime"] == "Yes" and row["JobSatisfaction"] <= 2:
        return "High Risk"
    elif row["Age"] < 30 and row["OverTime"] == "Yes" and row["MonthlyIncome"] < 4000:
        return "High Risk"
    elif row["EnvironmentSatisfaction"] <= 2 or row["WorkLifeBalance"] <= 2:
        return "Medium Risk"
    else:
        return "Low Risk"

# axis=1 means apply the function row by row.
df_clean["RetentionRiskSegment"] = df_clean.apply(assign_retention_risk, axis=1)

df_clean[[
    "Age", "OverTime", "MonthlyIncome", "JobSatisfaction", 
    "EnvironmentSatisfaction", "WorkLifeBalance", "RetentionRiskSegment", "Attrition"
]].head(15)

,Age,OverTime,MonthlyIncome,JobSatisfaction,EnvironmentSatisfaction,WorkLifeBalance,RetentionRiskSegment,Attrition
0,41,Yes,"5,993.00",4.00,2,1,Medium Risk,Yes
1,49,No,"5,130.00",2.00,3,3,Low Risk,No
2,37,Yes,"2,090.00",3.00,4,3,Low Risk,Yes
3,33,Yes,"2,909.00",3.00,4,3,Low Risk,No
4,27,No,"3,468.00",2.00,1,3,Medium Risk,No
5,32,No,"3,068.00",4.00,4,2,Medium Risk,No
6,59,Yes,"2,670.00",1.00,3,2,High Risk,No
7,30,No,"2,693.00",3.00,4,3,Low Risk,No
8,38,No,"9,526.00",3.00,4,3,Low Risk,No
9,36,No,"5,237.00",3.00,3,2,Medium Risk,No
10,35,No,"2,426.00",3.00,1,3,Medium Risk,No
11,29,Yes,"4,193.00",3.00,4,3,Low Risk,No
12,31,No,"2,911.00",3.00,1,2,Medium Risk,No
13,34,No,"2,661.00",4.00,2,3,Medium Risk,No
14,28,Yes,"2,028.00",3.00,3,3,High Risk,Yes

## 14. Use `lambda` for quick transformations

**Task:** Create compact labels using `lambda` functions.

**Goal:** Show when `lambda` is useful for short, simple transformations.

**Pandas concepts:** `apply(lambda x: ...)`.

In [33]:
# Convert distance to a simple near/far label.
df_clean["DistanceCategory"] = df_clean["DistanceFromHome"].apply(
    lambda x: "Far" if x >= 10 else "Near"
)

# Create a short department code using string slicing.
df_clean["DepartmentCode"] = df_clean["Department"].apply(lambda x: x[:3].upper())

# Create a simple income level label.
df_clean["IncomeLevel"] = df_clean["MonthlyIncome"].apply(
    lambda x: "High" if x >= 10000 else ("Medium" if x >= 5000 else "Low")
)

df_clean[["Department", "DepartmentCode", "DistanceFromHome", "DistanceCategory", "MonthlyIncome", "IncomeLevel"]].head(10)

               Department DepartmentCode  DistanceFromHome DistanceCategory  MonthlyIncome IncomeLevel
0                   Sales            SAL                 1             Near       5,993.00      Medium
1  Research & Development            RES                 8             Near       5,130.00      Medium
2  Research & Development            RES                 2             Near       2,090.00         Low
3  Research & Development            RES                 3             Near       2,909.00         Low
4  Research & Development            RES                 2             Near       3,468.00         Low
5  Research & Development            RES                 2             Near       3,068.00         Low
6  Research & Development            RES                 3             Near       2,670.00         Low
7  Research & Development            RES                24              Far       2,693.00         Low
8  Research & Development            RES                23              Far       9,526.00      Medium
9  Research & Development            RES                27              Far       5,237.00      Medium

## 15. Explore attrition by one categorical variable

**Business question:** Which departments have higher attrition rates?

**Task:** Group employees by department and calculate:

- number of employees
- number of employees who left
- attrition rate
- average monthly income
- average job satisfaction

**Pandas concepts:** `groupby()`, `agg()`, named aggregation, sorting.

In [34]:
department_summary = (
    df_clean
    .groupby("Department")
    .agg(
        employee_count=("AttritionFlag", "size"),
        attrition_count=("AttritionFlag", "sum"),
        attrition_rate=("AttritionFlag", "mean"),
        avg_monthly_income=("MonthlyIncome", "mean"),
        median_monthly_income=("MonthlyIncome", "median"),
        avg_job_satisfaction=("JobSatisfaction", "mean")
    )
    .sort_values("attrition_rate", ascending=False)
)

# Convert attrition rate to percentage for easier interpretation.
department_summary["attrition_rate"] = department_summary["attrition_rate"] * 100

department_summary.round(2)

,employee_count,attrition_count,attrition_rate,avg_monthly_income,median_monthly_income,avg_job_satisfaction
Department,,,,,,
Sales,446,92,20.63,"6,963.99","5,765.00",2.76
Human Resources,63,12,19.05,"6,502.26","3,978.50",2.60
Research & Development,961,133,13.84,"6,244.40","4,381.00",2.74

## 16. Explore attrition by multiple categorical variables

**Business question:** Does overtime appear to matter across departments?

**Task:** Group by both `Department` and `OverTime`.

**Goal:** Compare attrition rates for overtime vs. non-overtime employees within each department.

**Pandas concepts:** multi-column `groupby()`, `agg()`, `reset_index()`.

In [35]:
department_overtime_summary = (
    df_clean
    .groupby(["Department", "OverTime"])
    .agg(
        employee_count=("AttritionFlag", "size"),
        attrition_count=("AttritionFlag", "sum"),
        attrition_rate=("AttritionFlag", "mean"),
        avg_income=("MonthlyIncome", "mean"),
        avg_years_at_company=("YearsAtCompany", "mean")
    )
    .reset_index()
)

department_overtime_summary["attrition_rate"] = department_overtime_summary["attrition_rate"] * 100

department_overtime_summary.sort_values(["Department", "attrition_rate"], ascending=[True, False]).round(2)

               Department OverTime  employee_count  attrition_count  attrition_rate  avg_income  avg_years_at_company
1         Human Resources      Yes              17                5           29.41    6,656.06                  8.12
0         Human Resources       No              46                7           15.22    6,445.42                  6.91
3  Research & Development      Yes             271               74           27.31    6,279.49                  6.80
2  Research & Development       No             690               59            8.55    6,230.61                  6.89
5                   Sales      Yes             128               48           37.50    7,065.95                  6.93
4                   Sales       No             318               44           13.84    6,922.95                  7.43

## 17. Use `transform()` to compare each employee with their group

**Business question:** Is an employee paid above or below the average for their job role?

**Task:** For each employee, calculate:

- average monthly income for their job role
- difference between their income and job-role average
- whether they are below their job-role average

**Pandas concepts:** `groupby().transform()`, creating comparison columns.

In [36]:
# transform returns a Series with the same length as the original dataframe.
df_clean["JobRoleAvgIncome"] = df_clean.groupby("JobRole")["MonthlyIncome"].transform("mean")

df_clean["IncomeVsJobRoleAvg"] = df_clean["MonthlyIncome"] - df_clean["JobRoleAvgIncome"]

df_clean["BelowJobRoleAvgIncome"] = np.where(df_clean["IncomeVsJobRoleAvg"] < 0, "Yes", "No")

df_clean[[
    "JobRole", "MonthlyIncome", "JobRoleAvgIncome", 
    "IncomeVsJobRoleAvg", "BelowJobRoleAvgIncome", "Attrition"
]].head(10)

                     JobRole  MonthlyIncome  JobRoleAvgIncome  IncomeVsJobRoleAvg BelowJobRoleAvgIncome Attrition
0            Sales Executive       5,993.00          6,898.52             -905.52                   Yes       Yes
1         Research Scientist       5,130.00          3,255.95            1,874.05                    No        No
2      Laboratory Technician       2,090.00          3,292.88           -1,202.88                   Yes       Yes
3         Research Scientist       2,909.00          3,255.95             -346.95                   Yes        No
4      Laboratory Technician       3,468.00          3,292.88              175.12                    No        No
5      Laboratory Technician       3,068.00          3,292.88             -224.88                   Yes        No
6      Laboratory Technician       2,670.00          3,292.88             -622.88                   Yes        No
7      Laboratory Technician       2,693.00          3,292.88             -599.88                   Yes        No
8     Manufacturing Director       9,526.00          7,163.98            2,362.02                    No        No
9  Healthcare Representative       5,237.00          7,480.73           -2,243.73                   Yes        No

In [37]:
# Question: Do employees below their job-role average income have higher attrition?
income_gap_summary = (
    df_clean
    .groupby("BelowJobRoleAvgIncome")
    .agg(
        employee_count=("AttritionFlag", "size"),
        attrition_count=("AttritionFlag", "sum"),
        attrition_rate=("AttritionFlag", "mean"),
        avg_income_gap=("IncomeVsJobRoleAvg", "mean")
    )
)

income_gap_summary["attrition_rate"] = income_gap_summary["attrition_rate"] * 100
income_gap_summary.round(2)

                       employee_count  attrition_count  attrition_rate  avg_income_gap
BelowJobRoleAvgIncome
No                                620               87           14.03        1,878.25
Yes                               850              150           17.65       -1,370.02

## 18. Build a reusable summary function

**Task:** Write a function that summarizes attrition by any categorical column.

**Goal:** Avoid repeating the same groupby code again and again.

**Pandas concepts:** defining functions, `groupby()`, `agg()`, sorting, reuse.

In [38]:
def summarize_attrition_by(category_col):
    """
    Summarize employee count, attrition count, and attrition rate by a categorical column.
    
    Parameters
    ----------
    category_col : str
        Column name used for grouping.
    
    Returns
    -------
    pandas.DataFrame
        Summary table sorted by attrition rate.
    """
    summary = (
        df_clean
        .groupby(category_col)
        .agg(
            employee_count=("AttritionFlag", "size"),
            attrition_count=("AttritionFlag", "sum"),
            attrition_rate=("AttritionFlag", "mean"),
            avg_income=("MonthlyIncome", "mean"),
            avg_age=("Age", "mean")
        )
        .sort_values("attrition_rate", ascending=False)
    )
    
    summary["attrition_rate"] = summary["attrition_rate"] * 100
    return summary.round(2)

In [39]:
# Example 1: attrition by job role
summarize_attrition_by("JobRole")

                           employee_count  attrition_count  attrition_rate  avg_income  avg_age
JobRole
Sales Representative                   83               33           39.76    2,753.05    30.36
Laboratory Technician                 259               62           23.94    3,292.88    34.10
Human Resources                        52               12           23.08    4,290.88    35.50
Sales Executive                       326               57           17.48    6,898.52    36.89
Research Scientist                    292               47           16.10    3,255.95    34.24
Manufacturing Director                145               10            6.90    7,163.98    38.30
Healthcare Representative             131                9            6.87    7,480.73    39.81
Manager                               102                5            4.90   16,921.80    46.76
Research Director                      80                2            2.50   15,844.10    44.00

In [40]:
# Example 2: attrition by age group
summarize_attrition_by("AgeGroup")

          employee_count  attrition_count  attrition_rate  avg_income  avg_age
AgeGroup
Under 30             326               91           27.91    3,752.99    25.71
30-39                622               89           14.31    5,596.86    34.29
50+                  173               23           13.29   10,810.66    53.80
40-49                349               34            9.74    8,428.31    43.72

In [41]:
# Example 3: attrition by income level
summarize_attrition_by("IncomeLevel")

             employee_count  attrition_count  attrition_rate  avg_income  avg_age
IncomeLevel
Low                     750              160           21.33    3,226.55    33.58
Medium                  445               52           11.69    6,785.35    37.17
High                    275               25            9.09   14,825.64    45.63

## 19. Analyze numerical variables for employees who left vs. stayed

**Business question:** How do employees who left differ from employees who stayed?

**Task:** Compare average and median values for selected numerical columns by attrition status.

**Pandas concepts:** selecting columns, `groupby()`, multiple aggregation functions.

In [42]:
key_numeric_cols = [
    "Age", "MonthlyIncome", "DistanceFromHome", "YearsAtCompany", 
    "YearsInCurrentRole", "JobSatisfaction", "EnvironmentSatisfaction", 
    "WorkLifeBalance", "PercentSalaryHike"
]

attrition_numeric_summary = df_clean.groupby("Attrition")[key_numeric_cols].agg(["mean", "median", "min", "max"])

attrition_numeric_summary.round(2)

            Age                MonthlyIncome                             DistanceFromHome                 \
           mean median min max          mean   median      min       max             mean median min max
Attrition
No        37.56  36.00  18  60      6,789.84 5,163.00 1,051.00 19,999.00             8.92   7.00   1  29
Yes       33.61  32.00  18  58      4,829.44 3,408.00 1,009.00 19,859.00            10.63   9.00   1  29

          YearsAtCompany                YearsInCurrentRole                JobSatisfaction                   \
                    mean median min max               mean median min max            mean median  min  max
Attrition
No                  7.37   6.00   0  37               4.48   3.00   0  18            2.78   3.00 1.00 4.00
Yes                 5.13   3.00   0  40               2.90   2.00   0  15            2.51   3.00 1.00 4.00

          EnvironmentSatisfaction                WorkLifeBalance                PercentSalaryHike
                             mean median min max            mean median min max              mean median min max
Attrition
No                           2.77   3.00   1   4            2.78   3.00   1   4             15.23  14.00  11  25
Yes                          2.46   3.00   1   4            2.66   3.00   1   4             15.10  14.00  11  25

## 20. Find the highest-risk groups using grouped filters

**Business question:** Which groups are large enough to matter and have high attrition rates?

**Task:** Summarize attrition by job role, then filter to groups with at least 30 employees.

**Goal:** Avoid overreacting to tiny groups.

**Pandas concepts:** `groupby()`, `agg()`, filtering summary tables with `loc`.

In [43]:
jobrole_summary = summarize_attrition_by("JobRole")

# Filter to job roles with at least 30 employees.
large_jobrole_summary = jobrole_summary.loc[jobrole_summary["employee_count"] >= 30]

large_jobrole_summary.sort_values("attrition_rate", ascending=False)

                           employee_count  attrition_count  attrition_rate  avg_income  avg_age
JobRole
Sales Representative                   83               33           39.76    2,753.05    30.36
Laboratory Technician                 259               62           23.94    3,292.88    34.10
Human Resources                        52               12           23.08    4,290.88    35.50
Sales Executive                       326               57           17.48    6,898.52    36.89
Research Scientist                    292               47           16.10    3,255.95    34.24
Manufacturing Director                145               10            6.90    7,163.98    38.30
Healthcare Representative             131                9            6.87    7,480.73    39.81
Manager                               102                5            4.90   16,921.80    46.76
Research Director                      80                2            2.50   15,844.10    44.00

## 21. Create a pivot-style comparison table without visualization

**Business question:** How does attrition rate vary by age group and overtime status?

**Task:** Create a table where rows are age groups, columns are overtime status, and values are attrition rates.

**Pandas concepts:** `pivot_table()`.

In [44]:
age_overtime_pivot = pd.pivot_table(
    df_clean,
    values="AttritionFlag",
    index="AgeGroup",
    columns="OverTime",
    aggfunc="mean"
) * 100

age_overtime_pivot.round(2)

OverTime    No   Yes
AgeGroup
30-39     9.37 28.22
40-49     6.48 17.65
50+       8.62 22.81
Under 30 17.67 53.19

## 22. More complex case: build an HR action table

**Business question:** Which employee segments may deserve immediate HR review?

**Task:** Build a table by `RetentionRiskSegment`, `OverTime`, and `IncomeLevel`.

For each segment, calculate:

- number of employees
- attrition count
- attrition rate
- average monthly income
- average job satisfaction
- average years at company

Then keep only groups with at least 10 employees and sort by attrition rate.

**Pandas concepts:** multi-column groupby, named aggregation, filtering, sorting.

In [45]:
hr_action_table = (
    df_clean
    .groupby(["RetentionRiskSegment", "OverTime", "IncomeLevel"])
    .agg(
        employee_count=("AttritionFlag", "size"),
        attrition_count=("AttritionFlag", "sum"),
        attrition_rate=("AttritionFlag", "mean"),
        avg_income=("MonthlyIncome", "mean"),
        avg_job_satisfaction=("JobSatisfaction", "mean"),
        avg_years_at_company=("YearsAtCompany", "mean")
    )
    .reset_index()
)

hr_action_table["attrition_rate"] = hr_action_table["attrition_rate"] * 100

hr_action_table = hr_action_table.loc[hr_action_table["employee_count"] >= 10]

hr_action_table.sort_values("attrition_rate", ascending=False).round(2)

,RetentionRiskSegment,OverTime,IncomeLevel,employee_count,attrition_count,attrition_rate,avg_income,avg_job_satisfaction,avg_years_at_company
1,High Risk,Yes,Low,113,57,50.44,"2,959.85",2.15,4.22
13,Medium Risk,Yes,Low,44,18,40.91,"3,435.64",3.52,4.52
14,Medium Risk,Yes,Medium,49,14,28.57,"6,302.18",3.65,6.65
0,High Risk,Yes,High,33,9,27.27,"14,422.00",1.42,13.36
2,High Risk,Yes,Medium,40,10,25.00,"6,874.85",1.45,6.55
7,Low Risk,Yes,Low,45,9,20.00,"3,521.26",3.29,5.40
10,Medium Risk,No,Low,306,53,17.32,"3,252.58",2.77,4.89
8,Low Risk,Yes,Medium,42,7,16.67,"6,815.64",3.57,6.62
9,Medium Risk,No,High,106,11,10.38,"14,825.57",2.76,13.02
4,Low Risk,No,Low,242,23,9.50,"3,225.35",2.68,4.76
11,Medium Risk,No,Medium,186,17,9.14,"6,868.20",2.69,7.60
12,Medium Risk,Yes,High,27,2,7.41,"14,439.22",3.41,13.11
6,Low Risk,Yes,High,23,1,4.35,"14,756.78",3.65,12.52
5,Low Risk,No,Medium,128,4,3.12,"6,812.01",2.75,7.32
3,Low Risk,No,High,86,2,2.33,"15,120.36",2.67,12.28

## 23. Identify individual records for follow-up

**Business question:** Which employees match a high-risk profile?

**Task:** Use `loc` to find employees who:

- are in the High Risk segment
- work overtime
- have low or medium income
- have low job satisfaction

**Pandas concepts:** compound filtering, `loc`, selecting useful columns, sorting.

In [46]:
high_risk_employees = df_clean.loc[
    (df_clean["RetentionRiskSegment"] == "High Risk") &
    (df_clean["OverTime"] == "Yes") &
    (df_clean["IncomeLevel"].isin(["Low", "Medium"])) &
    (df_clean["JobSatisfaction"] <= 2),
    [
        "Age", "Department", "JobRole", "MonthlyIncome", "IncomeLevel",
        "OverTime", "JobSatisfaction", "EnvironmentSatisfaction", 
        "WorkLifeBalance", "YearsAtCompany", "Attrition"
    ]
]

high_risk_employees.sort_values(["Attrition", "MonthlyIncome"], ascending=[False, True]).head(20)

,Age,Department,JobRole,MonthlyIncome,IncomeLevel,OverTime,JobSatisfaction,EnvironmentSatisfaction,WorkLifeBalance,YearsAtCompany,Attrition
585,23,Research & Development,Laboratory Technician,"1,601.00",Low,Yes,1.00,3,3,0,Yes
892,19,Research & Development,Research Scientist,"1,859.00",Low,Yes,2.00,1,4,1,Yes
457,18,Sales,Sales Representative,"1,878.00",Low,Yes,2.00,2,3,0,Yes
636,35,Research & Development,Research Scientist,"2,022.00",Low,Yes,2.00,4,2,10,Yes
762,26,Research & Development,Research Scientist,"2,042.00",Low,Yes,1.00,1,3,3,Yes
100,37,Human Resources,Human Resources,"2,073.00",Low,Yes,1.00,3,3,3,Yes
1110,35,Research & Development,Laboratory Technician,"2,074.00",Low,Yes,1.00,1,3,1,Yes
336,29,Research & Development,Laboratory Technician,"2,119.00",Low,Yes,1.00,2,2,7,Yes
688,19,Sales,Sales Representative,"2,121.00",Low,Yes,2.00,4,4,1,Yes
1171,40,Research & Development,Laboratory Technician,"2,166.00",Low,Yes,1.00,1,1,4,Yes
357,21,Sales,Sales Representative,"2,174.00",Low,Yes,2.00,1,3,3,Yes
540,28,Research & Development,Research Scientist,"2,216.00",Low,Yes,2.00,1,3,7,Yes
952,31,Sales,Sales Representative,"2,302.00",Low,Yes,2.00,4,4,3,Yes
1353,34,Research & Development,Research Scientist,"2,307.00",Low,Yes,1.00,4,3,5,Yes
798,33,Research & Development,Research Scientist,"2,313.00",Low,Yes,2.00,1,3,2,Yes
589,29,Research & Development,Laboratory Technician,"2,319.00",Low,Yes,1.00,2,3,1,Yes
709,31,Research & Development,Research Scientist,"2,321.00",Low,Yes,1.00,3,3,3,Yes
1313,29,Human Resources,Human Resources,"2,335.00",Low,Yes,1.00,1,3,2,Yes
1279,44,Research & Development,Research Scientist,"2,342.00",Low,Yes,2.00,3,2,5,Yes
288,26,Research & Development,Laboratory Technician,"2,373.00",Low,Yes,2.00,1,3,3,Yes

## 24. Use `assign()` and method chaining

**Task:** Rewrite part of the analysis using method chaining.

**Goal:** Show a more advanced pandas style where multiple steps are connected.

This style is common in professional pandas code, but students should first understand the step-by-step version.

In [47]:
chained_summary = (
    df_clean
    .assign(
        IncomeBelow5000=lambda data: data["MonthlyIncome"] < 5000,
        ShortTenure=lambda data: data["YearsAtCompany"] < 3
    )
    .groupby(["IncomeBelow5000", "ShortTenure", "OverTime"])
    .agg(
        employee_count=("AttritionFlag", "size"),
        attrition_count=("AttritionFlag", "sum"),
        attrition_rate=("AttritionFlag", "mean"),
        avg_age=("Age", "mean")
    )
    .reset_index()
    .sort_values("attrition_rate", ascending=False)
)

chained_summary["attrition_rate"] = chained_summary["attrition_rate"] * 100
chained_summary.round(2)

   IncomeBelow5000  ShortTenure OverTime  employee_count  attrition_count  attrition_rate  avg_age
7             True         True      Yes              73               41           56.16    32.21
3            False         True      Yes              31               12           38.71    40.00
5             True        False      Yes             129               43           33.33    34.24
6             True         True       No             174               45           25.86    31.64
1            False        False      Yes             183               31           16.94    41.10
4             True        False       No             374               31            8.29    34.53
0            False        False       No             442               30            6.79    39.93
2            False         True       No              64                4            6.25    41.89

## 25. Final written interpretation

**Task:** Use pandas outputs to write a short business interpretation.

**Goal:** Practice turning tables into insights.

Answer these questions after running the notebook:

1. What is the overall attrition rate?
2. Which department has the highest attrition rate?
3. Which job roles have high attrition rates among reasonably large groups?
4. Does overtime appear related to attrition?
5. Do younger employees appear to have different attrition patterns?
6. Which risk segments should HR review first?
7. What data limitations should we mention before making decisions?

Important: These are exploratory findings. They show associations, not causal proof.

In [ ]:
# Useful final outputs to review before writing the interpretation.
print("Overall attrition rate:")
print((df_clean["AttritionFlag"].mean() * 100).round(2), "%")

print("Department summary:")
display(department_summary.round(2))

print("Age group summary:")
display(summarize_attrition_by("AgeGroup"))

print("Risk segment summary:")
display(summarize_attrition_by("RetentionRiskSegment"))

print("Age group by overtime pivot:")
display(age_overtime_pivot.round(2))

Overall attrition rate:
16.12 %
Department summary:

,employee_count,attrition_count,attrition_rate,avg_monthly_income,median_monthly_income,avg_job_satisfaction
Department,,,,,,
Sales,446,92,20.63,"6,963.99","5,765.00",2.76
Human Resources,63,12,19.05,"6,502.26","3,978.50",2.60
Research & Development,961,133,13.84,"6,244.40","4,381.00",2.74

Age group summary:

          employee_count  attrition_count  attrition_rate  avg_income  avg_age
AgeGroup
Under 30             326               91           27.91    3,752.99    25.71
30-39                622               89           14.31    5,596.86    34.29
50+                  173               23           13.29   10,810.66    53.80
40-49                349               34            9.74    8,428.31    43.72

Risk segment summary:

                      employee_count  attrition_count  attrition_rate  avg_income  avg_age
RetentionRiskSegment
High Risk                        186               76           40.86    5,835.39    35.17
Medium Risk                      718              115           16.02    6,537.77    37.37
Low Risk                         566               46            8.13    6,602.37    36.93

Age group by overtime pivot:

OverTime    No   Yes
AgeGroup
30-39     9.37 28.22
40-49     6.48 17.65
50+       8.62 22.81
Under 30 17.67 53.19

:

## 26. Optional student exercises

Use the same dataset and answer the following with pandas code:

1. Create a column called `PromotionDelayRisk`: `High` if `YearsSinceLastPromotion >= 4`, otherwise `Normal`.
2. Compare attrition rate by `PromotionDelayRisk`.
3. Create a column called `EarlyCareer`: `Yes` if `TotalWorkingYears <= 5`, otherwise `No`.
4. Compare attrition by `EarlyCareer` and `OverTime`.
5. For each department, calculate the average `MonthlyIncome`, then create a column showing whether each employee is above or below the department average.
6. Find the top 10 job roles with the largest gap between attrition rate for overtime and non-overtime employees.
7. Create a reusable function that summarizes any numerical column by attrition status.
8. Write 3 business recommendations based on your exploration.